### ISSUE TITLE
Thumbnail and View image not loading/broken, error 500 internal server error

### ISSUE THREAD

**Issue by janrauhl** [alexusmai/laravel-file-manager#286]
Hi @alexusmai greetings! 

Thanks for developing this amazing file manager! I am trying to use it in my project, however, I had problem in loading the images i uploaded. It wouldn't show the thumbnail in grid view, and when i click on 'view' it wouldn't show either. 

Below are the errors :

file-manager.js:15 CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token
initAxiosSettings @ file-manager.js:15
(anonymous) @ file-manager.js:13
(anonymous) @ file-manager.js:13
(anonymous) @ file-manager.js:13
y._withCommit @ file-manager.js:13
y.commit @ file-manager.js:13
commit @ file-manager.js:13
created @ file-manager.js:15
nt @ file-manager.js:7
Rn @ file-manager.js:7
e._init @ file-manager.js:7
o @ file-manager.js:7
an @ file-manager.js:7
init @ file-manager.js:7
h @ file-manager.js:7
p @ file-manager.js:7
(anonymous) @ file-manager.js:7
Ln.e._update @ file-manager.js:7
r @ file-manager.js:7
nr.get @ file-manager.js:7
nr @ file-manager.js:7
zn @ file-manager.js:7
_r.$mount @ file-manager.js:7
56d7 @ file-manager.js:15
n @ file-manager.js:1
0 @ file-manager.js:1
n @ file-manager.js:1
(anonymous) @ file-manager.js:1
(anonymous) @ file-manager.js:1
filemanager:50 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'fmSetLink')
    at Object.<anonymous> (filemanager:50:25)
    at file-manager.js:15:381053
preview:1 Failed to load resource: the server responded with a status of **500 (Internal Server Error)**
file-manager/thumbnails?disk=local&path=sample%2Fsample1.png&v=1644041643:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
file-manager/url?disk=local&path=sample%2Fsample1.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
file-manager.js:7 Uncaught (in promise) Error: Network Error
    at e.exports (file-manager.js:7:81590)
    at XMLHttpRequest.p.onerror (file-manager.js:17:61897)
preview:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
![Screenshot (10)](https://user-images.githubusercontent.com/76951397/152631215-00c40814-9e48-4150-92b4-81832cbcac38.png)
![Screenshot (11)](https://user-images.githubusercontent.com/76951397/152631217-86640a9f-6185-4c3a-83dd-204ad745de13.png)
![Screenshot (12)](https://user-images.githubusercontent.com/76951397/152631218-aab108c5-36a8-421d-ae24-3e0e6c6a89d1.png)

DevTools failed to load source map: Could not load content for http://127.0.0.1:8000/vendor/file-manager/js/app.b80d5059.js.map: Connection error: net::ERR_CONNECTION_REFUSED 

I followed the tutorial from: [https://therealprogrammer.com/laravel-file-manager-tutorial-example/](https://therealprogrammer.com/laravel-file-manager-tutorial-example/ )

**Comment by janrauhl** [comment]
Sorry, I just saw your comment in other similar issue on Imagick and GD installation, and I followed the guide released by [http://www.webassist.com/tutorials/Enabling-the-GD-library-setting](url) to enable GD, and it works! Thanks anyways
